name: Welcome to TechBytes

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.MY_REPO_ACCESS_TOKEN }}
          issue-message: "👋 Welcome to MyBlog! Feel free to explore and contribute."
          pr-message: "🎉 Congratulations on your first pull request in TechBytes!"
