name: Welcome to TechBytes

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to TechBytes! Feel free to explore and contribute."
          pr-message: "🎉 Congratulations on your first pull request in TechBytes!"
